from . import school_management
from . import student_management
from . import teacher_management
from . import school_tags
from . import student_result
from . import subject_list
from . import hr_inherit
from . import purchase_info
from . import sale_inherit
from . import purchase_report_attachment
from . import route_inherit
